### ISSUE TITLE
Deny for all roles does not work

### ISSUE THREAD

**Issue by xmav** [laminas/laminas-permissions-acl#35]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.10.0

#### Summary

Previously it was possible to deny access to specific resource for all roles (with Zend_Acl)
`$acl->deny(null, 'test1');` worked fine. 
But now this behavior is changed. I would confirm that it is expected (or bug)

#### Current behavior

$acl->deny(null, 'test1');
$acl->isAllowed($roleGuest, 'test1') (result is `true`)

#### How to reproduce

Add following test and run:
```
    public function testRoleDefaultRuleSetResource(): void
    {
        $roleGuest = new GenericRole('guest');
        $this->acl->addResource('test1')
            ->addRole($roleGuest)
            ->allow($roleGuest);
        $this->assertTrue($this->acl->isAllowed($roleGuest, 'test1'));

        $this->acl->deny(null, 'test1');
        $this->assertFalse($this->acl->isAllowed($roleGuest, 'test1'));
    }
```

#### Expected behavior

I would expect to get `false` as result after `$acl->deny(null, 'test1');`

**Comment by Ocramius** [comment]
Could you please verify the latest version where your test still passes? Sounds like a regression.

**Comment by xmav** [comment]
that's changed between zf1 `release-1.12.20` and zf\laminas `2.0.0`. Test passed with zf1 `release-1.12.20` but fails with zf\laminas `2.0.0`

**Comment by Ocramius** [comment]
Closing then: [`laminas/laminas-permission-acl:2.0.0`](https://github.com/laminas/laminas-permissions-acl/releases/tag/2.0.0) was first released in 2012, which was ~10y ago, and the library had been completely rewritten in `2.0.0` at that point. 

I initially left this open thinking it was a regression in 2.x, heh :D
